### ISSUE TITLE
Unable to See Storage Usage of Groups That I Am An Admin Of

### ISSUE THREAD

**Issue by stiefeljackal** [GuVAnj8Gv3RJ/NeosAccountDownloader#64]
Before 1.5, I was able to see the storage usage of the groups that I am an admin of. In 1.6, it looks like the `(admin)` tag is pushing the storage usage amount to the third line, which is invisible.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/0629d618-1533-4ef1-81c1-8fdd254156f0)

This is more than likely a side effect of fixing #26. Adjusting the width of the window does not fix this either.

**Comment by GuVAnj8Gv3RJ** [comment]
![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/132167543/f4516f52-a6da-4661-bdd2-4c923a19ed4c)
Admin is after the file space hmm. 

Its possible we failed to retrieve the storage for that group.

**Comment by GuVAnj8Gv3RJ** [comment]
I was unable to reproduce this. 

If you run the app in develop, you should be able to open Avalonia Dev tools with F12, this will enable you to sneak around and see what's going on. Its basically chrome dev tools.

**Comment by stiefeljackal** [comment]
Thank you for responding. I ran the Avalonia Dev tools before, so I can send you something. This is based on the current release of the app, so I will compile the current one at `master` and let you know. Give me a bit as I am currently assisting in an event at Neos right now.

**Comment by stiefeljackal** [comment]
Nevermind. I just noticed the `fix/groups-again` branch. I will use that to verify.

**Comment by GuVAnj8Gv3RJ** [comment]
That's just got some random crap on it to try to reproduce your issue. Master should be safe to repro this.

**Comment by stiefeljackal** [comment]
Okay. Switched to the master branch. It looks like it is still there.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/d58ca02a-a79a-48e6-93cb-a09c09969c9f)

The text value **(3.22 GB)** is there, but it looks like the width of the text block is 0 for some reason. It could be either the second text block occupying the whole second line when it has any text in it or something affecting the Groups component from outside the component or a combination of both.

**Comment by stiefeljackal** [comment]
I actually might have a lead for you. Upon unchecking and checking the `IsVisible` property, it rehydrated with the text, so perhaps the property is not notifying that it has a value... or maybe it is still something else.

<img width="739" alt="image" src="https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/63a9c932-81ee-483a-bac0-725e39bdab47">

**Comment by GuVAnj8Gv3RJ** [comment]
Something is setting it to invisible then, nothing in the bindings does this. Perhaps there is an error in the formatting.

**Comment by stiefeljackal** [comment]
I believe it is the formatting. `IsVisible` is checked initially; I just unchecked and rechecked it via the DevTools to see if the text needed to be rehydrated; this was the case.

**Comment by GuVAnj8Gv3RJ** [comment]
In a debug build avalonia logging is enabled. 

Stuff like this appears: " [DBG] [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #11671115)"

Do you have any of that in the log ifles?

**Comment by stiefeljackal** [comment]
I do. Check this out:

```
2023-07-27 00:10:50.942 -04:00 [INF] Language set to: English (United States)
2023-07-27 00:10:51.550 -04:00 [DBG] LogHost: Initializing to normal mode (.cctor)
2023-07-27 00:10:51.714 -04:00 [INF] Starting up Neos Account Downloader v1.6.0
2023-07-27 00:10:51.714 -04:00 [INF] Log Level: $Debug
2023-07-27 00:10:52.319 -04:00 [DBG] RoutedViewHost: Ready to show AccountDownloader.Views.GettingStartedView with autowired AccountDownloader.ViewModels.GettingStartedViewModel.
2023-07-27 00:10:56.176 -04:00 [DBG] RoutedViewHost: Ready to show AccountDownloader.Views.LoginView with autowired AccountDownloader.ViewModels.LoginViewModel.
2023-07-27 00:11:13.655 -04:00 [INF] Logging in user: StiefelJackal
2023-07-27 00:11:15.078 -04:00 [DBG] Updating user New:StiefelJackal, Old:Unauthenticated 
2023-07-27 00:11:15.993 -04:00 [INF] StiefelJackal Logged in successfully.
2023-07-27 00:11:15.993 -04:00 [DBG] Updating user New:StiefelJackal, Old:StiefelJackal 
2023-07-27 00:11:16.043 -04:00 [INF] Getting groups for: StiefelJackal
2023-07-27 00:11:16.093 -04:00 [DBG] RoutedViewHost: Ready to show AccountDownloader.Views.DownloadSelectionView with autowired Contacts:False, MessageHistory:False, InventoryWorlds:False, CloudVariableDefinitions:False, CloudVariableValues:False, Groups:.
2023-07-27 00:11:16.098 -04:00 [DBG] Updating user New:StiefelJackal, Old:StiefelJackal 
2023-07-27 00:11:16.413 -04:00 [INF] Got 4 groups for user.
2023-07-27 00:11:18.991 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #61795582)
2023-07-27 00:11:28.289 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.ColumnDefinition'.'IsVisible': 'Null value in expression '{empty}' at ''.'(ColumnDefinition #57201619)
2023-07-27 00:11:28.315 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '!.$parent[UserControl, 2]'.'(DataGridTextColumn #44335814)
2023-07-27 00:11:28.317 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #63478007)
2023-07-27 00:11:28.318 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #34431157)
2023-07-27 00:11:35.128 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.ColumnDefinition'.'IsVisible': 'Null value in expression '{empty}' at ''.'(ColumnDefinition #53535755)
2023-07-27 00:11:35.130 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '!.$parent[UserControl, 2]'.'(DataGridTextColumn #12059749)
2023-07-27 00:11:35.131 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #41428878)
2023-07-27 00:11:35.132 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #37315583)
2023-07-27 00:11:35.140 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.ColumnDefinition'.'IsVisible': 'Null value in expression '{empty}' at ''.'(ColumnDefinition #57201619)
2023-07-27 00:11:35.141 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Diagnostics.Controls.FilterTextBox'.'DataContext': 'Null value in expression '{empty}' at ''.'(FilterTextBox #25339754)
2023-07-27 00:11:35.147 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Diagnostics.Views.LayoutExplorerView'.'DataContext': 'Null value in expression '{empty}' at ''.'(LayoutExplorerView #39434429)
2023-07-27 00:11:35.148 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Diagnostics.Controls.FilterTextBox'.'DataContext': 'Null value in expression '{empty}' at ''.'(FilterTextBox #43154428)
2023-07-27 00:11:35.152 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #62545577)
2023-07-27 00:11:35.153 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #26039288)
2023-07-27 00:11:35.154 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #33027006)
2023-07-27 00:11:35.155 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '!.$parent[UserControl, 2]'.'(DataGridTextColumn #44335814)
2023-07-27 00:11:35.156 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #63478007)
2023-07-27 00:11:35.157 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Controls.DataGridTextColumn'.'IsVisible': 'Null value in expression '{empty}' at '$parent[UserControl, 2]'.'(DataGridTextColumn #34431157)
2023-07-27 00:11:35.161 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #28807604)
2023-07-27 00:11:35.162 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #57941852)
2023-07-27 00:11:35.163 -04:00 [DBG] [Binding]Error in binding to 'Avalonia.Media.GeometryDrawing'.'Brush': 'Null value in expression '{empty}' at '$parent[ToggleButton, 0]'.'(GeometryDrawing #51714621)
```

**Comment by GuVAnj8Gv3RJ** [comment]
Should be fixed in #70 

Or at least it should say "Error" or something IDK

**Comment by GuVAnj8Gv3RJ** [comment]
@stiefeljackal is this fixed?

**Comment by stiefeljackal** [comment]
@GuVAnj8Gv3RJ Let me check with the latest release.

**Comment by stiefeljackal** [comment]
@GuVAnj8Gv3RJ Naw. It is still the same. Want me to check out the code and perform a PR for you? I wouldn't mind helping you out with this task as there are more urgent ones.

**Comment by GuVAnj8Gv3RJ** [comment]
If you can figure it out go for it.

**Comment by stiefeljackal** [comment]
I figured it out. See #75.
